version: "3"

services:
  postgres:
    image: postgres:15-alpine
    container_name: sonar-db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

  sonarqube:
    build: .
    container_name: sonarqube-server
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/${DATABASE_NAME}
      - SONAR_JDBC_USERNAME=${DATABASE_USER}
      - SONAR_JDBC_PASSWORD=${DATABASE_PASSWORD}
      - SONAR_SEARCH_JAVAOPTS=-Xms512m -Xmx512m
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  postgres:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
